### ISSUE TITLE
Object attachment is not working

### ISSUE THREAD

**Issue by KeliangH** [KavrakiLab/vicon_object_server#15]
There seems to be an issue with object attachment. 
Reproduction:
1. Open up vicon object server setup with moveit + UR5 setup. 
2. Bring up RViz, we see the objects like we should.
3. In the Scene Objects panel, click the checkbox by any object, and select a frame to attach it.
4. It doesn't attach.
This same error also shows up when I try to attach objects by a service call to /apply_planning_scene. This service call works when the scene objects are not managed by the vicon object server.

Possible cause:
I think the error is in /vicon_object_server_server/src/main.cpp in MoveItInteraction::callback and in MoveItInteraction::update. But I need some help understanding what these functions are supposed to achieve to fix them. At this point, they seem to keep record which collision objects are mentioned in the scene spewed out by moveit, but this information is immediately discarded next time moveit sends a scene.

**Comment by KeliangH** [comment]
Let me know if you know how this part was supposed to work so I can fix this issue. This is blocking my experiments.

**Comment by BryceStevenWilley** [comment]
I'm looking at this now. I know that currently, it works when calling `move_group.attachObject("Can1");` in a running script/program, but I'm not sure how those mechanisms work through RViz or `/apply_planning_scene` though.

When running the existing demo, we get an error saying: `[ERROR] [1513615448.392185772]: World object 'Can1' does not exist. Cannot move.`, but the script continues execution and there are no problems, so I'm not sure what to make of it.

**Comment by BryceStevenWilley** [comment]
Follow-up: this is fixed by Juan's PR #18.  Once that's merged, we need to make a server side "disableAndAttach" call that will disable the object so vic_obj_ser doesn't keep publishing it, and then call attach on the given object and the given manipulator.
